### PR TITLE
Add yubico-c pkgconfig file

### PR DESCRIPTION
**Pull request by kloczek**
pkgconfig file allows easier detection of the yubico-c library and its
version.

### CODE REVIEW

**Comment by klali** [comment]
Thanks!

The contributions are attributed to "Your Name <you@example.com>" would you mind fixing that?

**Comment by kloczek** [comment]
Sorry to ask .. what exactly you want me to do? :)

**Comment by klali** [comment]
The two commits have "Your Name you@example.com" as author, I'd like them to be properly attributed to you.

**Comment by kloczek** [comment]
"Tomasz Kłoczko <kloczek@github.com>" that would allways work :P

Thx.
PS. When this PR will be accepted and commited will try to go over other yubi projects to add use pkgconfig to detect and use yubico-c library :)

**Comment by klali** [comment]
I can fix it for you, but that will require force pushing the master branch of your fork.

I'm not sure that it's a good idea to update all current dependencies to use pkg-config, they will atleast have to retain the old way of finding the library at least to avoid having to depend on a new unreleased version.

**Comment by kloczek** [comment]
Moment .. so you want me to put line with my name and email in commit comment?
How can I do that? Just do `git commit --amend <comit_hash>` and force push those modifications?

> I'm not sure that it's a good idea to update all current dependencies to use pkg-config, they will atleast have to retain the old way of finding the library at least to avoid having to depend on a new unreleased version.

That IMO depends only on kind of synchronisation between repositories.
If yubico-c new version will be released first than it will be possible to merge changes in other repos. In mean time all prose PRs could be queued.

**Comment by klali** [comment]
I already fixed it up and merged this.

You're welcome to open pull requests in repos depending on this.

**Comment by kloczek** [comment]
Is it possible to make soon new release with that commit to allow use pkgconfig detection in other software?

**Pull request closed without merging**
